apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable
  labels:
    app: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stable
  template:
    metadata:
      labels:
        app: stable
    spec:
      containers:
      - name: frontend
        image: noizysthlm/flask-app
        ports:
        - containerPort: 80
